import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/Layout';
import SearchBar from '../components/SearchBar';

export default function Home() {
  return (
    <Layout showHeaderInitially={true}>
      <Head>
        <title>Recyclopedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gradient-to-b from-orange to-purple h-60 -mb-32"></div>
      <SearchBar activeBackgroundColor="#F1EDEA" />
      <div className="container">
        <div className="grid col-span-2"></div>
      </div>
    </Layout>
  );
}
